#!/bin/bash

# NOTE: This script is used to upload the firmware for ROS2 MBot

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -lt 1 ] || [ $# -gt 2 ]; 
then
  echo "Usage: $0 [load | run | flash | disable] <uf2_file>"
  exit $E_BADARGS
fi

OPERATION=$1
UF2_FILE=$2

if grep -q "Raspberry Pi 5" /proc/device-tree/model; then
  echo "Detected Raspberry Pi 5, entering $1 mode..."
  BTLD_PIN=4
  RUN_PIN=17
  GPIO_CHIP="gpiochip4"
else
  echo "ERROR: Unknown hardware!"
  exit 1
fi

sleep 0.1

case "$OPERATION" in
    "load"|"run"|"flash"|"disable")
        # notice that for all cases, we consdier the RUN_PIN is high
        # which set by services/mbot_start_networking.py 
        case "$OPERATION" in
            "load")
                echo "Loading action for $UF2_FILE..."
                if [ -n "$UF2_FILE" ]; then
                    gpioset $GPIO_CHIP $RUN_PIN=0
                    sleep 0.1
                    gpioset $GPIO_CHIP $BTLD_PIN=0
                    sleep 0.5
                    gpioset $GPIO_CHIP $RUN_PIN=1
                    sleep 0.5
                    sudo picotool load $UF2_FILE
                    sleep 0.5
                else
                    echo "Missing UF2 file for 'load' operation."
                fi
                ;;
            "run")
                echo "Running action for loaded UF2_FILE..."
                gpioset $GPIO_CHIP $RUN_PIN=0
                sleep 0.1
                gpioset $GPIO_CHIP $BTLD_PIN=1
                sleep 0.5
                gpioset $GPIO_CHIP $RUN_PIN=1
                sleep 1
                ;;
            "flash")
                echo "Flashing action for $UF2_FILE..."
                if [ -n "$UF2_FILE" ]; then
                    gpioset $GPIO_CHIP $RUN_PIN=0
                    sleep 0.1
                    gpioset $GPIO_CHIP $BTLD_PIN=0
                    sleep 0.5
                    gpioset $GPIO_CHIP $RUN_PIN=1
                    sleep 0.5
                    sudo picotool load $UF2_FILE
                    sleep 0.5
                    gpioset $GPIO_CHIP $BTLD_PIN=1
                    sleep 0.5
                    sudo picotool reboot
                else
                    echo "Missing UF2 file for 'flash' operation."
                fi
                ;;
            "disable")
                echo "Disable action..."
                gpioset $GPIO_CHIP $BTLD_PIN=1
                sleep 0.5
                gpioset $GPIO_CHIP $RUN_PIN=0
                sleep 1
                ;;
        esac
        ;;
    *)
        echo "'$OPERATION' is not a valid operation. Please provide one of the following operations: load, run, flash, disable"
        ;;
esac
